### ISSUE TITLE
project can't build with the latest webrtc anymore.

### ISSUE THREAD

**Issue by shi-yan** [auscaster/webrtc-native-to-browser-peerconnection-example#2]
Hello,

Thank you very much for this example. but it doesn't build with the latest webrtc (due to api name changing). I tried to fix it, there are too many changes I need to do.

I'm wondering what exactly you changed to the c++ project (peerconnection_client / peerconnection_server)? if not too much, maybe modifying the latest peerconnection example in the webrtc code is easier than making this project work with the latest webrtc.

Thank you

**Comment by auscaster** [comment]
@shi-yan Thanks for researching this, did you have any luck getting video to display?

DTLS SRTP is required for FireFox to display the video stream.

**Comment by edsut** [comment]
I managed to get things to build and run successfully based on Kam's original code.
The working fork is here: https://github.com/edsut/webrtc-native-to-browser-peerconnection-example
Since this is my first attempt at github, if there's something else I should do (i.e. a pull request) let me know.  Thanks again for the code!

**Comment by auscaster** [comment]
Great work Ed! So you were able to get the stream to play in FF and Chrome?
If so please initiate a pull request and I will update the code.

Oh, and welcome to github :) +1

**Comment by edsut** [comment]
Ok done... Hopefully I did the pull request correctly.  
One thing I think will be messed up for you is that I changed the README for use in my copy of this, which doesn't apply to you... Lemme know if I did something (else) wrong.
